// products.js - Medicine Catalog for MediCare Pharmaceuticals
const DEFAULT_MEDICINES = [
    {
        id: 1,
        name: 'Paracetamol 500mg',
        category: 'Pain Relief',
        dosage: '500mg tablet, take 1-2 tablets every 4-6 hours',
        whoCanTake: 'Adults and children over 12 years.',
        description: 'Effective pain reliever and fever reducer.',
        sideEffects: 'Rare at recommended doses. Overdose may cause liver damage.',
        manufacturer: 'PharmaCorp Ltd.',
        price: 5.99,
        icon: '💊',
        expirationDate: '2026-12-31',
        stock: 120
    },
    {
        id: 2,
        name: 'Amoxicillin 250mg',
        category: 'Antibiotic',
        dosage: '250mg capsule, take every 8 hours as prescribed',
        whoCanTake: 'Prescribed by doctor for bacterial infections.',
        description: 'Broad-spectrum penicillin antibiotic.',
        sideEffects: 'Nausea, diarrhea, skin rash.',
        manufacturer: 'BioGen Healthcare',
        price: 12.49,
        icon: '💊',
        expirationDate: '2025-11-15',
        stock: 45
    },
    {
        id: 3,
        name: 'Metformin 500mg',
        category: 'Diabetes',
        dosage: '500mg tablet, take with meals as prescribed',
        whoCanTake: 'Type 2 diabetes patients under medical supervision.',
        description: 'Helps control blood sugar levels.',
        sideEffects: 'Stomach upset, metallic taste.',
        manufacturer: 'GlucoMed Inc.',
        price: 9.75,
        icon: '💉',
        expirationDate: '2026-05-20',
        stock: 78
    },
    {
        id: 4,
        name: 'Omeprazole 20mg',
        category: 'Digestive',
        dosage: '20mg capsule once daily before breakfast',
        whoCanTake: 'Adults with acid reflux, GERD, or stomach ulcers.',
        description: 'Proton pump inhibitor that reduces stomach acid.',
        sideEffects: 'Headache, stomach pain.',
        manufacturer: 'DigestiveCare Labs',
        price: 8.25,
        icon: '💊',
        expirationDate: '2026-03-10',
        stock: 63
    },
    {
        id: 5,
        name: 'Cetirizine 10mg',
        category: 'Allergy',
        dosage: '10mg tablet once daily',
        whoCanTake: 'Adults and children over 6 years for allergy relief.',
        description: 'Antihistamine that relieves allergy symptoms.',
        sideEffects: 'Mild drowsiness, dry mouth.',
        manufacturer: 'AllerClear Pharma',
        price: 4.50,
        icon: '🤧',
        expirationDate: '2026-08-01',
        stock: 200
    },
    {
        id: 6,
        name: 'Atorvastatin 20mg',
        category: 'Cardiac',
        dosage: '20mg tablet once daily at bedtime',
        whoCanTake: 'Adults with high cholesterol under medical guidance.',
        description: 'Statin medication that lowers cholesterol.',
        sideEffects: 'Muscle pain, digestive issues.',
        manufacturer: 'HeartGuard Pharmaceuticals',
        price: 14.99,
        icon: '❤️',
        expirationDate: '2026-09-30',
        stock: 55
    },
    {
        id: 7,
        name: 'Vitamin D3 1000IU',
        category: 'Vitamins',
        dosage: '1000IU tablet once daily with food',
        whoCanTake: 'Adults and children over 12.',
        description: 'Essential vitamin for bone health.',
        sideEffects: 'Very rare at recommended doses.',
        manufacturer: 'VitaPlus Nutrition',
        price: 3.99,
        icon: '☀️',
        expirationDate: '2027-01-15',
        stock: 300
    },
    {
        id: 8,
        name: 'Ibuprofen 400mg',
        category: 'Pain Relief',
        dosage: '400mg tablet, take 1 tablet every 6-8 hours with food',
        whoCanTake: 'Adults and children over 12. Avoid if stomach ulcers.',
        description: 'Non-steroidal anti-inflammatory drug.',
        sideEffects: 'Stomach irritation, heartburn.',
        manufacturer: 'PharmaCorp Ltd.',
        price: 6.49,
        icon: '💊',
        expirationDate: '2026-08-20',
        stock: 80
    },
    {
        id: 9,
        name: 'Loratadine 10mg',
        category: 'Allergy',
        dosage: '10mg tablet once daily',
        whoCanTake: 'Adults and children over 2 years.',
        description: 'Non-drowsy antihistamine for seasonal allergies.',
        sideEffects: 'Mild headache, dry mouth.',
        manufacturer: 'AllerClear Pharma',
        price: 5.25,
        icon: '🌿',
        expirationDate: '2026-07-12',
        stock: 150
    },
    {
        id: 10,
        name: 'Amlodipine 5mg',
        category: 'Cardiac',
        dosage: '5mg tablet once daily',
        whoCanTake: 'Adults with high blood pressure.',
        description: 'Calcium channel blocker that relaxes blood vessels.',
        sideEffects: 'Swelling in ankles, dizziness.',
        manufacturer: 'HeartGuard Pharmaceuticals',
        price: 10.99,
        icon: '🫀',
        expirationDate: '2026-06-30',
        stock: 40
    },
    {
        id: 11,
        name: 'Simvastatin 20mg',
        category: 'Cardiac',
        dosage: '20mg tablet once daily in the evening',
        whoCanTake: 'Adults with high cholesterol.',
        description: 'Lowers LDL cholesterol and triglycerides.',
        sideEffects: 'Muscle pain, joint pain.',
        manufacturer: 'GenScript Pharma',
        price: 13.75,
        icon: '💓',
        expirationDate: '2025-10-10',
        stock: 12
    },
    {
        id: 12,
        name: 'Azithromycin 500mg',
        category: 'Antibiotic',
        dosage: '500mg tablet once daily for 3 days',
        whoCanTake: 'Prescribed for bacterial infections.',
        description: 'Macrolide antibiotic that stops bacterial growth.',
        sideEffects: 'Diarrhea, nausea, abdominal pain.',
        manufacturer: 'BioGen Healthcare',
        price: 15.99,
        icon: '💊',
        expirationDate: '2025-09-01',
        stock: 3
    },
    {
        id: 13,
        name: 'Levothyroxine 50mcg',
        category: 'Hormone',
        dosage: '50mcg tablet once daily on empty stomach',
        whoCanTake: 'Patients with hypothyroidism under medical supervision.',
        description: 'Replacement thyroid hormone.',
        sideEffects: 'Hair loss, weight changes if dose too high.',
        manufacturer: 'ThyroCare Inc.',
        price: 7.99,
        icon: '🦋',
        expirationDate: '2026-11-22',
        stock: 90
    },
    {
        id: 14,
        name: 'Multivitamin Complete',
        category: 'Vitamins',
        dosage: '1 tablet daily with a meal',
        whoCanTake: 'Adults of all ages.',
        description: 'Comprehensive blend of essential vitamins and minerals.',
        sideEffects: 'May cause stomach upset on empty stomach.',
        manufacturer: 'VitaPlus Nutrition',
        price: 11.49,
        icon: '💪',
        expirationDate: '2027-03-05',
        stock: 250
    }
];